Repository sensu-plugins/sensu-plugins-network-checks, pull requests merged in 2018-03, with the labels that each got.

#75 [CVE-2017-8418] - updating rubocop dependency.
  .rubocop.yml
  .travis.yml
  CHANGELOG.md
  Gemfile
  Rakefile
  bin/check-banner.rb
  bin/check-jsonwhois-domain-expiration.rb
  bin/check-mtu.rb
  bin/check-multicast-groups.rb
  bin/check-netfilter-conntrack.rb
  bin/check-netstat-tcp.rb
  bin/check-ping.rb
  bin/check-ports-bind.rb
  bin/check-ports-nmap.rb
  bin/check-ports.rb
  bin/check-rbl.rb
  bin/check-socat.rb
  bin/check-whois-domain-expiration-multi.rb
  bin/check-whois-domain-expiration.rb
  bin/metrics-interface.rb
  bin/metrics-net.rb
  bin/metrics-netif.rb
  bin/metrics-netstat-tcp.rb
  bin/metrics-ping.rb
  bin/metrics-sockstat.rb
  lib/sensu-plugins-network-checks.rb
  lib/sensu-plugins-network-checks/version.rb
  sensu-plugins-network-checks.gemspec
  test/check-mtu_spec.rb
  test/check-ports_spec.rb
  test/metrics-sockstat_spec.rb
  test/plugin_stub.rb
  test/spec_helper.rb
Labels: Impact: Breaking Change, Type: Security

#72 Migrate NF conntrack check into ruby script
  CHANGELOG.md
  README.md
  bin/check-netfilter-conntrack.rb
  bin/check-netfilter-conntrack.sh
  test/check-netfilter-conntrack_spec.rb
Labels: Type: Enhancement

#76 [CVE-2017-17042] update vulnerable `yard` dependency
  CHANGELOG.md
  sensu-plugins-network-checks.gemspec
Labels: Status: Needs Review, Type: Security
